export const messages = {
  INCORRECT_CREDENTIALS: "Credentials are incorrect",
  USER_ALREADY_EXISTS: "Provided email is already in use. Please go to login page",
  USER_NOT_FOUND: "User not found",
  FAILED_TO_SEND_OTP: "Failed to send Otp",
  FAILED_TO_STORE_OTP: "Failed to store Otp",
  OTP_SENT_SUCCESSFULLY: "Otp sent successfully",
  OTP_INCORRECT: "Incorrect Otp",
  OTP_EXPIRED: "Otp has expired",
  OTP_VERIFIED: "Otp verified successfully",
  EMAIL_ALREADY_EXIST: "Email already exist",
  USER_CREATION_FAILED: "User creation failed",
  USER_UPDATION_FAILED: "Failed to update user",
  USER_CREATION_SUCCESS: "User created successfully",
  USER_DELETION_FAILED: "Failed to delete user",
  USER_DELETED_SUCCESSFULLY: "User deleted successfully",
  USER_FETCHED_SUCCESSFULLY: "User fetched successfully",
  EMAIL_NOT_FOUND: "Email not found",
  INCORRECT_PASSWORD: "Incorrect password",
  LOGIN_SUCCESS: "login successfully",
  USER_TYPE_UPDATED: "User type updated successfully",
  SERVICE_REQUIRED_AND_NOT_EMPTY: "Service is required and should not be empty",
  SERVICE_ID_INVALID: "One or more service IDs are invalid",
  SERVICE_ID_NOT_EXIST: "One or more service IDs do not exist",
  SERVICE_SET_SUCCESS: "User service has been set successfully",
  SERVICE_GET_SUCCESS: "Service has been fetched successfully",
  USER_TYPE_ALREADY_SET: "You have already set your user type",
  FILE_UPLOAD_SUCCESS: "File uploaded successfully",
  INVALID_PHONE_NUMBER: "Invalid phone number",
  VERIFICATION_SUCCESS: "Phone number verified successfully",
  USER_UPDATION_SUCCESS: "User updated successfully",
  GUARD_CREATION_FAILED: "Failed to create a new guard",
  GUARD_CREATION_SUCCESS: "Guard created successfully",
  GUARD_FETCHED_SUCCESS: "Guards fetched successfully",
  GUARD_UPDATION_FAILED: "Failed to update guard",
  PASSWORD_CANNOT_BE_SAME: "Password cannot be the same as the previous one",
  PASSWORD_RESET_SUCCESSFULLY: "Password has been successfully reset",
  PASSWORD_RESET_FAILED: "Password reset failed",
  PASSWORD_NOT_FOUND: "Please reset your password",
  NO_BANK_ACCOUNT_FOUND: "No bank account found",
  BANK_ACCOUNT_FETCHED_SUCCESS: "Bank account fetched successfully",
  GUARD_SIGN_UP_SUCCESS: "Guard sign up successfully completed",
  USER_ID_REQUIRED: "User ID is required",
  PHONE_NUMBER_ALREADY_EXISTS: "Phone number already exists",
  COMPANY_NOT_FOUND: "Company not found",
  BANK_ACCOUNT_UPDATE_FAILED: "Failed to update bank account",
  BANK_ACCOUNT_UPDATED_SUCCESSFULLY: "Bank account updated successfully",
};
